# Generated by Django 5.2.1 on 2025-06-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'disponivel'), ('RESERVADA', 'reservada'), ('INATIVA', 'inativa')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('CLIENTE', 'cliente'), ('ADMINISTRADOR', 'administrador')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField()),
                ('status', models.CharField(choices=[('ATIVO', 'ativo'), ('CANCELADO', 'cancelado')], max_length=10)),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
